wandb:
  project: symdex
  #name: test
  group: null
  #space_id: 'fame' # only to host on huggingface
  #mode: 'online'
  #tags: null
  #entity: null
  settings:
    ignore_globs: [ '*.pt' ]
    start_method: 'fork'

